data_path: "data"
expand: True
split: 0.2
random_state: 42
ds1_name: "sentiment-analysis-for-financial-news.zip"
ds2_name: "stockmarket-sentiment-dataset.zip"
ds3_name: "stock-markettweets-lexicon-data.zip"
ds1_path: "ankurzing/sentiment-analysis-for-financial-news"
ds2_path: "yash612/stockmarket-sentiment-dataset"
ds3_path: "utkarshxy/stock-markettweets-lexicon-data"
df1_name: "all-data.csv"
df2_name: "stock_data.csv"
df3_name: "tweets_labelled_09042020_16072020.csv"
save_path: "data/temp"
save_path_raw: "data/raw"
train_name: "train.csv"
test_name: "test.csv"