input_path: 'data/temp'
output_dir: 'results'
model_name: 'bert-base-cased'
tokenizer_name: 'bert-base-cased'
padding: 'max_length'
evaluation_strategy: 'epoch'
num_train_epochs: 5
log_level: 'error'
report_to: 'none'
per_device_train_batch_size: 8
metric_name: 'accuracy'
save_strategy: 'no'
